### ISSUE TITLE
Error when the body of the pull request is too large

### ISSUE THREAD

**Issue by hkusu** [hkusu/slack-integration#30]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/6157540/121385329-fb5ce500-c983-11eb-92b4-ba739a3e4692.png">

**Comment by hkusu** [comment]
As defined in `action.yml`, event input receives a GitHub event as JSON.

```
event:
  description: ''
  default: ${{ toJson(github.event) }}
  required: false
```

This input is too large, causing an error on the GitHub Actions platform.
